package FinalProject;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Books extends javax.swing.JFrame {
DefaultTableModel model;
String eatcomapny="Elizbeth Gliberth";
String angcomapny="Frank McCourt";
String historycomapny="Kostova";
String atlascompany="Ayn Rand";
String uncompany="Millians";
String shortcompany="Billy";
String tippingcompany="Moris";
String javaltcompany="Daniel lang";
String ccltcompany="Dietal and dieltal";

double total;

    
    public Books() {
        initComponents();
         model=(DefaultTableModel)jTableCustom.getModel();
    }
    public void stationary()    //User Define Method
    {
        String a=c1.getSelectedItem().toString();
        int price = 0;
        
        if(a.equals("Eat,Pray,Love "))
        {
            price=750;
            tdi.setText(String.valueOf(price));
        int quantity=Integer.parseInt(t2.getText());    
        double rate=quantity*price;
        total+=rate;
        model.insertRow(model.getRowCount(),new Object[]{a,eatcomapny,quantity,price,rate});
        
        }
        else if(a.equals("Angela's Ashes"))
        {
            price=900;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
            double rate=quantity*price;
            total+=rate;
        
            model.insertRow(model.getRowCount(),new Object[]{a,angcomapny,quantity,price,rate});
            
        }
        else if(a.equals("The Historian"))
        {
            price=1000;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
       double rate=quantity*price;
       total+=rate;
       
       model.insertRow(model.getRowCount(),new Object[]{a,historycomapny,quantity,price,rate});
            
        }
        else if(a.equals("Atlas Shrugged"))
        {
            price=600;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
       double rate=quantity*price;
       total+=rate;
       
       model.insertRow(model.getRowCount(),new Object[]{a,atlascompany,quantity,price,rate});
     
        }
        else if(a.equals("The Unbearable"))
        {
            price=500;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
       double rate=quantity*price;
       total+=rate;
       
       model.insertRow(model.getRowCount(),new Object[]{a,uncompany,quantity,price,rate});
     
        }
        else if(a.equals("A Short History"))
        {
            price=1900;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
       double rate=quantity*price;
       total+=rate;
       
       model.insertRow(model.getRowCount(),new Object[]{a,shortcompany,quantity,price,rate});
     
        }
        else if(a.equals("The Tipping Point"))
        {
            price=1500;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
       double rate=quantity*price;
       total+=rate;
       
       model.insertRow(model.getRowCount(),new Object[]{a,tippingcompany,quantity,price,rate});
     
        }
         else if(a.equals("Java Beginner Guide"))
        {
            price=3000;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
       double rate=quantity*price;
       total+=rate;
       
       model.insertRow(model.getRowCount(),new Object[]{a,javaltcompany,quantity,price,rate});
     
        }
         else if(a.equals("How to Program C++"))
        {
            price=900;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
       double rate=quantity*price;
       total+=rate;
       
       model.insertRow(model.getRowCount(),new Object[]{a,ccltcompany,quantity,price,rate});
     
        }
       
       tdisplay.setText(String.valueOf(total));
       
      
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCustom = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JButton();
        javax.swing.JButton badd = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tdi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tdisplay = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTableCustom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Author", "Per Pieces", "Price", "Rate"
            }
        ));
        jScrollPane1.setViewportView(jTableCustom);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 840, 190);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Select Items");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 120, 90, 17);

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Eat,Pray,Love ", "Angela's Ashes", "The Historian", "Atlas Shrugged", "The Unbearable", "A Short History", "The Tipping Point", "Java Beginner Guide", "How to Program C++" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1);
        c1.setBounds(120, 120, 140, 30);

        b1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(51, 51, 51));
        b1.setText("Payment");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(720, 410, 110, 30);

        badd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        badd.setText("Add");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });
        jPanel1.add(badd);
        badd.setBounds(450, 120, 100, 30);
        jPanel1.add(t2);
        t2.setBounds(450, 160, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 160, 70, 20);

        tdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdiActionPerformed(evt);
            }
        });
        jPanel1.add(tdi);
        tdi.setBounds(120, 160, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Price");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 160, 50, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TOTAL BiLL");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 410, 80, 30);

        tdisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdisplayActionPerformed(evt);
            }
        });
        jPanel1.add(tdisplay);
        tdisplay.setBounds(580, 410, 120, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home transpe.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 100, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/2nd book.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 860, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed

    }//GEN-LAST:event_c1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
 JOptionPane.showMessageDialog(null, "Thankx For Shopping\nIn Fazii Super Market");
    dispose();  // for close previous frame
        Menu m=new Menu();
        m.setVisible(true);

    }//GEN-LAST:event_b1ActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        stationary();      // Process of Calculations
    }//GEN-LAST:event_baddActionPerformed

    private void tdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdiActionPerformed

    private void tdisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdisplayActionPerformed

    }//GEN-LAST:event_tdisplayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
        dispose();  // for close previous frame
        Menu m=new Menu();
        m.setVisible(true);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCustom;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField tdi;
    private javax.swing.JTextField tdisplay;
    // End of variables declaration//GEN-END:variables
}
