package FinalProject;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class Grocery extends javax.swing.JFrame {
DefaultTableModel model;
String bcomapny="LU",bbatchno="bxkh009";        //Biscuit
String jucomapny="Nestle",jubatchno="Juad888";  //Juice
String ricomapny="Super",ribatchno="riqw776";   //Rice
String sucompany="Rafhan Mills",subatchno="su99001";    //Shugar
String micompany="Gourment",mibatchno="mi66543";        //Milk
String mmcompany="None",mmbatchno="mmx8xx6";            //Meat
String ckncompany="None",cknbatchno="ckn5568";          //Chicken
double total;
    public Grocery() {
        initComponents();
        model=(DefaultTableModel)jTableCustom.getModel();
    }
    public void doo()
    {
        String a=c1.getSelectedItem().toString();
        int price = 0;
        
        if(a.equals("Biscuit"))
        {
            price=12;
            tdi.setText(String.valueOf(price));
        int quantity=Integer.parseInt(t2.getText());    
        double rate=quantity*price;
        total+=rate;
        model.insertRow(model.getRowCount(),new Object[]{a,bcomapny,bbatchno,quantity,price,rate});
        
        }
        else if(a.equals("Juice"))
        {
            price=30;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
            double rate=quantity*price;
            total+=rate;
        
            model.insertRow(model.getRowCount(),new Object[]{a,jucomapny,jubatchno,quantity,price,rate});
            
        }
        else if(a.equals("Rice 10/kg"))
        {
            price=700;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
       double rate=quantity*price;
       total+=rate;
       
       model.insertRow(model.getRowCount(),new Object[]{a,ricomapny,ribatchno,quantity,price,rate});
            
        }
        else if(a.equals("Shugar 10/kg"))
        {
            price=500;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
       double rate=quantity*price;
       total+=rate;
       
       model.insertRow(model.getRowCount(),new Object[]{a,sucompany,subatchno,quantity,price,rate});
     
        }
        else if(a.equals("Milk"))
        {
            price=40;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
       double rate=quantity*price;
       total+=rate;
       
       model.insertRow(model.getRowCount(),new Object[]{a,micompany,mibatchno,quantity,price,rate});
     
        }
        else if(a.equals("Meat"))
        {
            price=450;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
       double rate=quantity*price;
       total+=rate;
       
       model.insertRow(model.getRowCount(),new Object[]{a,mmcompany,mmbatchno,quantity,price,rate});
     
        }
        else if(a.equals("Chicken"))
        {
            price=250;
            tdi.setText(String.valueOf(price));
       int quantity=Integer.parseInt(t2.getText());
       double rate=quantity*price;
       total+=rate;
       
       model.insertRow(model.getRowCount(),new Object[]{a,ckncompany,cknbatchno,quantity,price,rate});
     
        }
       
       tdisplay.setText(String.valueOf(total));
       
      
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCustom = new javax.swing.JTable();
        tdisplay = new javax.swing.JTextField();
        javax.swing.JButton badd = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        bhome = new javax.swing.JButton();
        tdi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Select Items");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Price");

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Biscuit", "Juice", "Rice 10/kg", "Shugar 10/kg", "Milk", "Meat", "Chicken", " " }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Quantity");

        b1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(51, 51, 51));
        b1.setText("Choose");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jTableCustom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Company", "Batch Number", "Quantity", "Price", "Rate"
            }
        ));
        jScrollPane1.setViewportView(jTableCustom);

        tdisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdisplayActionPerformed(evt);
            }
        });

        badd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        badd.setText("Add");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });

        bhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home transpe.png"))); // NOI18N
        bhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhomeActionPerformed(evt);
            }
        });

        tdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TOTAL BiLL");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bag 3.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(bhome, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(tdi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(tdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bhome, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tdi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel5)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        doo();      // Process of Calculations 
    }//GEN-LAST:event_baddActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
       
       
    }//GEN-LAST:event_c1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        
    }//GEN-LAST:event_b1ActionPerformed

    private void bhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhomeActionPerformed
        
        dispose();  // for close previous frame
        Menu m=new Menu();
        m.setVisible(true);
       
    }//GEN-LAST:event_bhomeActionPerformed

    private void tdisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdisplayActionPerformed
    	
        
        
    }//GEN-LAST:event_tdisplayActionPerformed

    private void tdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdiActionPerformed
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grocery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton bhome;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCustom;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField tdi;
    private javax.swing.JTextField tdisplay;
    // End of variables declaration//GEN-END:variables
}
